[[s2n_tls]]
arch = "aarch64"
git-tree-sha1 = "df53db1808543c2afd3df8d9e6415c4b25a1f522"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "e42b981c9d7d25bae94ff4f5cb424e395292aa2a7d6876127dc544a10c378cd1"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.7.2+0/s2n_tls.v1.7.2.aarch64-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "aarch64"
git-tree-sha1 = "105d24b074109fc667255389619d9f91efe0fa3e"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "0f232e076349aa71410fa12cef9c23d8b6d32372c75d070c632ebd14fc4d0265"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.7.2+0/s2n_tls.v1.7.2.aarch64-linux-musl.tar.gz"
[[s2n_tls]]
arch = "aarch64"
git-tree-sha1 = "51200f0b5095bbc1c556bdd8b3d414a20922cd9e"
os = "freebsd"

    [[s2n_tls.download]]
    sha256 = "ee833fd436a473de8204eb557dc04141854600440ff7dce8021c55e4d7bf0ab6"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.7.2+0/s2n_tls.v1.7.2.aarch64-unknown-freebsd.tar.gz"
[[s2n_tls]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e341b2365160df80ed086bf358ddb4b7f724572"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "e4c6b6147f4cc6d1c9b94074d1383bca71bae4388d951220916bf348a7b41134"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.7.2+0/s2n_tls.v1.7.2.armv6l-linux-gnueabihf.tar.gz"
[[s2n_tls]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "10a09010360371b74e7d2ec1626944802a942892"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "c48a2ade6e1bd1154fb0a84bdcc20e707c97121bebfb3855118ab5c7f0fc59f5"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.7.2+0/s2n_tls.v1.7.2.armv6l-linux-musleabihf.tar.gz"
[[s2n_tls]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "970463ba95f42c70c8b9a821b21c3b8f4fe08270"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "7396e15902df3543620f61fd0e6759674f43bfaba2ae3a160e02b9e489065e6d"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.7.2+0/s2n_tls.v1.7.2.armv7l-linux-gnueabihf.tar.gz"
[[s2n_tls]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d4ee9773463ec7f8256d90d0a4994d06d411f7ed"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "308b6dd14257dcddf00d2629389d31e450df99917e34a4ec38452341f839b246"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.7.2+0/s2n_tls.v1.7.2.armv7l-linux-musleabihf.tar.gz"
[[s2n_tls]]
arch = "i686"
git-tree-sha1 = "8bc4fc34efbb01e3932d3e2374c912c61b91b623"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "cf455a2ccd135df4f813dbd92b30bcfe1ab462057d12d55dfcafe63b01e8e905"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.7.2+0/s2n_tls.v1.7.2.i686-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "i686"
git-tree-sha1 = "23d464bb5605db7dfde9090edc7a76ab6aa9831d"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "7bbc8d7af1009896f799860bbb5944d783506e5e69b27abdd871ca62c03b9bd1"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.7.2+0/s2n_tls.v1.7.2.i686-linux-musl.tar.gz"
[[s2n_tls]]
arch = "powerpc64le"
git-tree-sha1 = "b7374362ab7ab97254d645974370754fcff62b9b"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "cce7eedfb9129e189c0cffd2cb8d5af11fc55f726cb3fa3144ffa81ef1e561f6"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.7.2+0/s2n_tls.v1.7.2.powerpc64le-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "riscv64"
git-tree-sha1 = "23a85f5d2728034b66d2b440adff72eabe075e06"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "1cf18a1e22c99bfb101b6c1994eec599d5fcd2899528bcb6bc234963a6f8a18f"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.7.2+0/s2n_tls.v1.7.2.riscv64-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "x86_64"
git-tree-sha1 = "42baa665080f5e358ed6e7c1183224b23b241189"
libc = "glibc"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "75e77f6eb69dfaec53d14a3c94932f5b2fb56e31f3fc78cbe22a00e04480f24f"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.7.2+0/s2n_tls.v1.7.2.x86_64-linux-gnu.tar.gz"
[[s2n_tls]]
arch = "x86_64"
git-tree-sha1 = "73241c597c32a222b080d00f343c29e445dfe4ab"
libc = "musl"
os = "linux"

    [[s2n_tls.download]]
    sha256 = "3481419a4960f7f555b3c8f902e5bc68b34678d1487ac2fe71a3aa292b01f92e"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.7.2+0/s2n_tls.v1.7.2.x86_64-linux-musl.tar.gz"
[[s2n_tls]]
arch = "x86_64"
git-tree-sha1 = "7b0a4d3ccf7cf851468178090b2858a6657488ca"
os = "freebsd"

    [[s2n_tls.download]]
    sha256 = "640ced1e6d3f018374ace2e106473100e76f34a6e1a0f7debc7580bb6fa7ba1f"
    url = "https://github.com/JuliaBinaryWrappers/s2n_tls_jll.jl/releases/download/s2n_tls-v1.7.2+0/s2n_tls.v1.7.2.x86_64-unknown-freebsd.tar.gz"
